Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/test.py", line 7, in <module>
    run = args.run_idx
AttributeError: 'Namespace' object has no attribute 'run_idx'
