Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/checkDatasetSize.py", line 77, in <module>
    os.chdir("../../../../../../speed")
FileNotFoundError: [Errno 2] No such file or directory: '../../../../../../speed'
